---
name: Build Docker image

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/**"
      - "README.md"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        id: build1
        uses: docker/build-push-action@v6
        with:
          tags: app:ci
          push: false
        env:
          SOURCE_DATE_EPOCH: 0
      - name: Report image digest
        run: echo "Digest ${{ steps.build1.outputs.digest }}"

      - name: Build image
        id: build2
        uses: docker/build-push-action@v6
        with:
          tags: app:ci
          push: false
        env:
          SOURCE_DATE_EPOCH: 0
      - name: Report image digest
        run: echo "Digest ${{ steps.build2.outputs.digest }}"
